services:
  backend:
    build: ./backend/recipeservice
    ports:
      - "5000:5000"
    env_file: ./backend/recipeservice/.env

  frontend:
    build: ./frontend/ai-recipe-ui--app
    ports:
      - "3000:3000"
    env_file: ./frontend/ai-recipe-ui--app/.env
