version: "3.8"

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - recipe_service
      - openai_service
    env_file: ./api_gateway/.env

  auth_service:
    build: ./auth_service
    env_file: ./auth_service/.env
    ports:
      - "5001:5001"

  recipe_service:
    build: ./recipe_service
    env_file: ./recipe_service/.env
    ports:
      - "5002:5002"

  openai_service:
    build: ./openai_service
    env_file: ./openai_service/.env
    ports:
      - "5003:5003"
