version: "3.8"

services:
  apigateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - recipeservice
      - openaiservice
    env_file: ./apigateway/.env

  authservice:
    build: ./authservice
    env_file: ./authservice/.env
    ports:
      - "5001:5001"

  recipeservice:
    build: ./recipeservice
    env_file: ./recipeservice/.env
    ports:
      - "5002:5002"

  openaiservice:
    build: ./openaiservice
    env_file: ./openaiservice/.env
    ports:
      - "5003:5003"
